export const SNIPPET_LANGUAGES = [
  "plaintext",
  "javascript",
  "typescript",
  "jsx",
  "tsx",
  "python",
  "go",
  "rust",
  "java",
  "c",
  "cpp",
  "csharp",
  "css",
  "html",
  "json",
  "sql",
  "bash",
  "yaml",
  "markdown",
] as const

export type SnippetLanguage = (typeof SNIPPET_LANGUAGES)[number]

export const SNIPPET_LANGUAGE_LABELS: Record<SnippetLanguage, string> = {
  plaintext: "Plain Text",
  javascript: "JavaScript",
  typescript: "TypeScript",
  jsx: "JSX",
  tsx: "TSX",
  python: "Python",
  go: "Go",
  rust: "Rust",
  java: "Java",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  css: "CSS",
  html: "HTML",
  json: "JSON",
  sql: "SQL",
  bash: "Bash",
  yaml: "YAML",
  markdown: "Markdown",
}
